# Generated by Django 4.2.9 on 2024-01-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='food_info',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food_info',
            name='start',
            field=models.DateField(auto_now=True),
        ),
    ]
