# Generated by Django 4.2.9 on 2024-01-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0002_alter_food_info_expiration_alter_food_info_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='expiration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food_info',
            name='start',
            field=models.DateField(),
        ),
    ]
