# Generated by Django 4.2.9 on 2024-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0003_alter_food_info_expiration_alter_food_info_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='expiration',
            field=models.DateField(),
        ),
    ]
